version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-ppassword", "-e", "SELECT 1"]
      timeout: 1s
      retries: 10

  web:
    image: $DOCKER_USERNAME/django-app:latest  # Folosește imaginea din Docker Hub
    container_name: django-app
#    build: .
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    environment:
      - DOCKERIZED=true
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: