pipeline {
    agent any
    environment {
        DOCKER_USERNAME = credentials('DOCKER_USERNAME')
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/mirunaaf/SelfcareDocker.git'
            }
        }

        stage('Deploy to Amazon Linux EC2') {
            steps {
                sh 'bash jenkins/deploy_django.sh'
            }
        }
    }
}
