---
- name: Configure EC2 and Deploy Django App
  hosts: ec2
  become: yes
  vars:
    ansible_host: "{{ ansible_host }}"

  tasks:
    - name: Update package lists
      yum:
        name: '*'
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to Docker group
        command: usermod -aG docker ec2-user

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: 'u+x'

    - name: Download latest docker-compose.yml
      get_url:
        url: "https://raw.githubusercontent.com/mirunaaf/SelfcareDocker/main/docker-compose.yml"
        dest: /home/ec2-user/docker-compose.yml
        mode: '0644'

    - name: Deploy containers
      shell: |
        docker-compose down
        docker-compose pull
        docker image prune -af --filter "reference=mirunaf/django-app"  # deletes old versions
        docker-compose up -d
      args:
        chdir: /home/ec2-user/


